import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {catalog} from '../public/asset-lab/catalog.js';
import {AssetController,features} from '../public/asset-lab/controller.js';
const defaults=Object.fromEntries(Object.entries(features).map(([k,v])=>[k,v.default]));
// Recording boundary catches non-finite geometry and canvas state leaks across shared instances.
function recorder(){let depth=0;const calls=[];const gradient={addColorStop(...a){calls.push(['stop',...a]);}};const ctx=new Proxy({}, {set(obj,k,v){obj[k]=v;calls.push([k,typeof v==='object'?'gradient':v]);return true;},get(obj,k){if(k in obj)return obj[k];return (...args)=>{for(const n of args)if(typeof n==='number')assert.ok(Number.isFinite(n),k+' must receive finite geometry');if(k==='save')depth++;if(k==='restore')depth--;assert.ok(depth>=0);calls.push([k,...args]);if(k==='createRadialGradient')return gradient;};}});return {ctx,calls,depth:()=>depth};}
test('36 unique modules, 12 families of three, manifest and control contract agree',()=>{assert.equal(catalog.length,36);assert.equal(new Set(catalog.map(a=>a.id)).size,36);assert.equal(new Set(catalog.map(a=>a.name)).size,36);const manifest=JSON.parse(fs.readFileSync(new URL('../public/asset-lab/variants.json',import.meta.url)));assert.equal(manifest.count,36);assert.deepEqual(manifest.assets.map(a=>a.id),catalog.map(a=>a.id));for(const f of new Set(catalog.map(a=>a.family)))assert.equal(catalog.filter(a=>a.family===f).length,3);for(const a of catalog){assert.ok(a.duration>0);assert.equal(typeof a.draw,'function');assert.deepEqual(a.supports,Object.keys(features));}});
test('all variants seek deterministically, balance canvas state, clean endpoints and respect zero/hidden',()=>{const signatures=new Set();for(const a of catalog){for(const p of [.1,.25,.49,.56,.75,.9]){const r=recorder();a.draw(r.ctx,a.duration*p,defaults);assert.equal(r.depth(),0,a.id);const repeat=recorder();a.draw(repeat.ctx,a.duration*p,defaults);assert.deepEqual(r.calls,repeat.calls);if(p===.49)signatures.add(JSON.stringify(r.calls));}for(const [t,o]of [[0,defaults],[a.duration,defaults],[a.duration/2,{...defaults,visible:false}],[a.duration/2,{...defaults,intensity:0}]]){const r=recorder();a.draw(r.ctx,t,o);assert.equal(r.calls.length,0,a.id+' must leave host background intact');}}assert.equal(signatures.size,36);});
test('saved override follows asset identity, not A/B selection order',()=>{const c=new AssetController(catalog);c.setAsset('v01','palette','cinnabar');c.setGlobal('palette','moon');assert.equal(c.resolve('v01').palette,'cinnabar');assert.equal(c.resolve('v36').palette,'moon');const d=new AssetController([...catalog].reverse());d.restore(c.snapshot());assert.equal(d.resolve('v01').palette,'cinnabar');assert.equal(d.resolve('v36').palette,'moon');});
